#!/bin/sh
# Creates the 1Password item for the GMO Coin API key and (re)generates the
# local git-ignored .env.1password file that `op run` uses to inject GMOCOIN_API_KEY /
# GMOCOIN_API_SECRET at runtime. The key values live only in 1Password;
# nothing secret is written to disk.
#
# Usage:
#   scripts/setup-1password.sh                     # vault=Private, item=gmocoin-api-test
#   scripts/setup-1password.sh --vault Work --item gmocoin-api-prod
#
# Requires the 1Password CLI (`op`) with app integration enabled
# (1Password app -> Settings -> Developer -> Integrate with 1Password CLI).
set -eu

VAULT="Private"
ITEM="gmocoin-api-test"
while [ $# -gt 0 ]; do
    case "$1" in
        --vault) VAULT="$2"; shift 2 ;;
        --item)  ITEM="$2";  shift 2 ;;
        *) echo "usage: setup-1password.sh [--vault <vault>] [--item <item>]"; exit 1 ;;
    esac
done

HERE="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$HERE/QuantConnect.GMOCoinBrokerage/.env.1password"

command -v op >/dev/null 2>&1 || {
    echo "ERROR: 1Password CLI (op) not found."
    echo "  macOS : brew install 1password-cli"
    echo "  Windows: winget install AgileBits.1Password.CLI"
    exit 1
}
op whoami >/dev/null 2>&1 || {
    if ! op account list >/dev/null 2>&1 || [ -z "$(op account list 2>/dev/null)" ]; then
        echo "ERROR: no 1Password account is configured for the op CLI."
        echo "  1. Install / sign in to the 1Password desktop app"
        echo "  2. 1Password app -> Settings -> Developer -> 'Integrate with 1Password CLI' -> ON"
        echo "  3. Re-run this script"
    else
        echo "ERROR: a 1Password account is configured but the CLI session is not authorized."
        echo
        echo "Fix (recommended, persistent): enable the app integration:"
        echo "  1Password app -> Settings -> Developer -> 'Integrate with 1Password CLI' -> ON"
        echo "  then re-run this script and approve the 1Password prompt."
        echo
        echo "Alternative (this shell only, ~30 min session):"
        echo '  eval $(op signin)'
        echo "  then re-run this script from the same shell."
    fi
    exit 1
}

if op item get "$ITEM" --vault "$VAULT" >/dev/null 2>&1; then
    echo "Item '$ITEM' already exists in vault '$VAULT' — keeping it."
    echo "(To rotate the key, edit the item in the 1Password app or run:"
    echo "  op item edit \"$ITEM\" --vault \"$VAULT\" api-key=... api-secret=... )"
else
    # hidden input; values never appear in shell history or on screen
    printf "GMO Coin API key    : "
    stty -echo; read -r API_KEY; stty echo; printf "\n"
    printf "GMO Coin API secret : "
    stty -echo; read -r API_SECRET; stty echo; printf "\n"
    [ -n "$API_KEY" ] && [ -n "$API_SECRET" ] || { echo "ERROR: empty key/secret"; exit 1; }

    op item create --category "API Credential" --vault "$VAULT" --title "$ITEM" \
        "api-key[text]=$API_KEY" \
        "api-secret[password]=$API_SECRET" >/dev/null
    unset API_KEY API_SECRET
    echo "Created 1Password item: $VAULT/$ITEM"
fi

# (re)generate the local git-ignored env file with the chosen vault/item references
cat > "$ENV_FILE" <<EOF
# 1Password secret references for \`op run\` — LOCAL ONLY (git-ignored).
# No real values, but vault/item names are environment-specific metadata;
# only env.1password.sample is committed.
# Generated by scripts/setup-1password.sh (vault=$VAULT, item=$ITEM).
# Usage (from the repo root):
#   op run --env-file=QuantConnect.GMOCoinBrokerage/.env.1password -- <command>
# or the shorthand wrapper:
#   scripts/op-run.sh <command>
GMOCOIN_API_KEY="op://$VAULT/$ITEM/api-key"
GMOCOIN_API_SECRET="op://$VAULT/$ITEM/api-secret"
EOF
echo "Wrote $ENV_FILE"

# verify that op can resolve the references (prints first 4 chars only)
HEAD="$(op read "op://$VAULT/$ITEM/api-key" | cut -c1-4)"
echo "Verification: op read api-key -> ${HEAD}... OK"
echo
echo "Next steps:"
echo "  scripts/op-run.sh dotnet run --project QuantConnect.GMOCoinBrokerage/tools/AssetsCheck"
