# Creates the 1Password item for the GMO Coin API key and (re)generates the
# local git-ignored .env.1password file that `op run` uses to inject GMOCOIN_API_KEY /
# GMOCOIN_API_SECRET at runtime. The key values live only in 1Password;
# nothing secret is written to disk.
#
# Usage (run scripts\setup-1password.cmd from cmd.exe/PowerShell to bypass
# ExecutionPolicy, or invoke this .ps1 directly if your policy allows):
#   scripts\setup-1password.cmd                              # vault=Private, item=gmocoin-api-test
#   scripts\setup-1password.cmd -Vault Work -Item gmocoin-api-prod
#
# Requires the 1Password CLI (`op`) with app integration enabled
# (1Password app -> Settings -> Developer -> Integrate with 1Password CLI).
param(
    [string]$Vault = "Private",
    [string]$Item = "gmocoin-api-test"
)

$repoRoot = Split-Path -Parent $PSScriptRoot
$envFile = Join-Path $repoRoot "QuantConnect.GMOCoinBrokerage\.env.1password"

if (-not (Get-Command op -ErrorAction SilentlyContinue)) {
    Write-Host "ERROR: 1Password CLI (op) not found. Install with: winget install AgileBits.1Password.CLI"
    exit 1
}

# The session check must run WITHOUT stream redirection: when stdout/stderr are
# piped, op treats the session as non-interactive and fails immediately instead
# of triggering the 1Password app-integration authorization prompt.
# (Also: under $ErrorActionPreference='Stop', redirecting a native command's
# stderr turns any op warning into a script-terminating NativeCommandError.)
Write-Host "Checking 1Password CLI session (approve the 1Password prompt if it appears)..."
op whoami
if ($LASTEXITCODE -ne 0) {
    $accounts = op account list 2>$null
    if ($LASTEXITCODE -ne 0 -or -not $accounts) {
        Write-Host "ERROR: no 1Password account is configured for the op CLI."
        Write-Host "  1. Install / sign in to the 1Password desktop app"
        Write-Host "  2. 1Password app -> Settings (設定) -> Developer (開発者) ->"
        Write-Host "     'Integrate with 1Password CLI (1Password CLI と連携)' -> ON"
        Write-Host "  3. Re-run this script"
        exit 1
    }
    Write-Host "ERROR: a 1Password account is configured but the CLI session is not authorized."
    Write-Host ""
    Write-Host "Fix (recommended, persistent): enable the app integration:"
    Write-Host "  1Password app -> Settings (設定) -> Developer (開発者) ->"
    Write-Host "  'Integrate with 1Password CLI (1Password CLI と連携)' -> ON"
    Write-Host "  then re-run this script and approve the 1Password prompt."
    Write-Host ""
    Write-Host "Alternative (this PowerShell window only, ~30 min session):"
    Write-Host '  Invoke-Expression $(op signin)'
    Write-Host "  then re-run this script from the same window."
    exit 1
}

op item get $Item --vault $Vault 2>$null | Out-Null
if ($LASTEXITCODE -eq 0) {
    Write-Host "Item '$Item' already exists in vault '$Vault' - keeping it."
    Write-Host "(To rotate the key, edit the item in the 1Password app.)"
} else {
    # hidden input; values never appear in console or history
    $keySecure = Read-Host -Prompt "GMO Coin API key" -AsSecureString
    $secretSecure = Read-Host -Prompt "GMO Coin API secret" -AsSecureString
    $key = [System.Net.NetworkCredential]::new("", $keySecure).Password
    $secret = [System.Net.NetworkCredential]::new("", $secretSecure).Password
    if (-not $key -or -not $secret) {
        Write-Host "ERROR: empty key/secret"
        exit 1
    }

    op item create --category "API Credential" --vault $Vault --title $Item `
        "api-key[text]=$key" "api-secret[password]=$secret" | Out-Null
    $created = $LASTEXITCODE
    $key = $null; $secret = $null
    if ($created -ne 0) {
        Write-Host "ERROR: op item create failed (exit $created)"
        exit 1
    }
    Write-Host "Created 1Password item: $Vault/$Item"
}

# (re)generate the local git-ignored env file with the chosen vault/item references
@"
# 1Password secret references for ``op run`` - LOCAL ONLY (git-ignored).
# No real values, but vault/item names are environment-specific metadata;
# only env.1password.sample is committed.
# Generated by scripts/setup-1password.ps1 (vault=$Vault, item=$Item).
# Usage (from the repo root):
#   op run --env-file=QuantConnect.GMOCoinBrokerage/.env.1password -- <command>
# or the shorthand wrapper:
#   scripts\op-run.cmd <command>          (macOS/Linux: scripts/op-run.sh)
GMOCOIN_API_KEY="op://$Vault/$Item/api-key"
GMOCOIN_API_SECRET="op://$Vault/$Item/api-secret"
"@ | Out-File -FilePath $envFile -Encoding utf8
Write-Host "Wrote $envFile"

# verify that op can resolve the references (prints first 4 chars only)
$value = op read "op://$Vault/$Item/api-key"
if ($LASTEXITCODE -ne 0 -or -not $value) {
    Write-Host "ERROR: op read verification failed"
    exit 1
}
Write-Host "Verification: op read api-key -> $($value.Substring(0, [Math]::Min(4, $value.Length)))... OK"
Write-Host ""
Write-Host "Next steps:"
Write-Host "  scripts\op-run.cmd dotnet run --project QuantConnect.GMOCoinBrokerage/tools/AssetsCheck"
exit 0
